In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# MSE Loss (mean squared error)

Creates a criterion that measures the mean squared error (squared L2 norm) between each element in the input xx and target yy.

In [2]:
sample_size = 3
number_features = 1

input = torch.arange(sample_size*number_features).reshape(sample_size, number_features) * 1.0
print(input)

tensor([[0.],
        [1.],
        [2.]])


In [3]:
target = torch.arange(2, sample_size*number_features+2).reshape(sample_size, number_features) * 1.0
print(target)

tensor([[2.],
        [3.],
        [4.]])


In [4]:
mes_loss = nn.MSELoss(reduction='mean')

In [5]:
output = mes_loss(input, target)
print(output)

tensor(4.)


## understand mse loss

In [6]:
custom_output = ((target - input)**2).mean()
print(custom_output)

tensor(4.)


# L1 Loss

Creates a criterion that measures the mean absolute error (MAE) between each element in the input x and target y.

In [7]:
l1_loss = nn.L1Loss(reduction='mean')

In [8]:
output = l1_loss(input, target)
print(output)

tensor(2.)


## understand l1 loss

In [9]:
custom_output = ((target - input).abs()).mean()
print(custom_output)

tensor(2.)


# NLLLoss

The negative log likelihood loss. It is useful to train a classification problem with C classes.

Input: (N, C), where C = number of classes

Target: (N)
    
Output: If reduction is 'none', shape (N) Otherwise, scalar.

In [10]:
sample_size = 3
output_size = 4

input = torch.arange(sample_size*output_size).reshape(sample_size, output_size) * 1.0
print(input)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [11]:
target = torch.tensor([1,0,3])
print(target)

tensor([1, 0, 3])


In [12]:
nll_loss = nn.NLLLoss(reduction="none")

In [13]:
output = nll_loss(input, target)
print(output)

tensor([ -1.,  -4., -11.])


In [14]:
nll_loss = nn.NLLLoss(reduction="mean")

In [15]:
output = nll_loss(input, target)
print(output)

tensor(-5.3333)


In [16]:
(-1 + -4 + -11)/3

-5.333333333333333

## understand nll loss

Select specific columns of each row in a torch Tensor

In [17]:
input.gather(1, target.view(-1,1))
#target.view(-1,1).shape
#torch.Size([3, 1])

tensor([[ 1.],
        [ 4.],
        [11.]])

In [18]:
(-1 * input.gather(1, target.view(-1,1))).mean()

tensor(-5.3333)

# CrossEntropyLoss

In [19]:
# sample＿size x class_size

inputs_ts = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], requires_grad=True) # Only Tensors of floating point and complex dtype can require gradients

# the first sample belongs to the first class, the second sample belongs to the third class
target_ts = torch.tensor([0,2], dtype=torch.long)

print(inputs_ts)
print(target_ts)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor([0, 2])


In [20]:
cross_entroy_loss = nn.CrossEntropyLoss(reduction="mean")

In [21]:
output = cross_entroy_loss(inputs_ts, target_ts)
print(output)

tensor(1.4076, grad_fn=<NllLossBackward0>)


## understand cross entropy loss

cross_entropy_loss = softmax + log + nllloss

In [24]:
def custom_cross_entropy(input, target):
    #step1: softmax
    softmax_value = F.softmax(inputs_ts)
    
    #step2: log
    log_softmax_value = torch.log(softmax_value)
    
    #step3:nllloss
    output = F.nll_loss(log_softmax_value, target)
    return output

In [25]:
custom_output = custom_cross_entropy(inputs_ts, target_ts)
print(custom_output)

tensor(1.4076, grad_fn=<NllLossBackward0>)


/tmp/ipykernel_1800998/3043229066.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  softmax_value = F.softmax(inputs_ts)
