In [1]:
import torch

# 1 create tensor by picking a factory function in pytorch

## 1.1 using factory function

Factory Functions

A factory function is a function that produces a new tensor. There are many factory functions available in PyTorch (both in Python and C++), which differ in the way they initialize a new tensor before returning it. All factory functions adhere to the following general “schema”:
~~~
torch.<function-name>(<function-specific-options>, <sizes>, <tensor-options>)
~~~

In [10]:
tensor = torch.rand((2,3))
print(tensor)

tensor([[0.3434, 0.8420, 0.1121],
        [0.8763, 0.1778, 0.8208]])


In [11]:
#1.1.2 Passing Function-Specific Parameters
tensor_int = torch.randint(10, (2, 3))
print(tensor_int)

tensor([[9, 6, 9],
        [2, 4, 7]])


## 1.2 create tensor from existing data

* torch::from_blob function

* torch::tensor function

In [14]:
data_vector1d = [1,2,3,4]
print(data_vector1d)

[1, 2, 3, 4]


In [15]:
data_vector2d = [[1,2,3,4],[2,3,4,5]]
print(data_vector2d)

[[1, 2, 3, 4], [2, 3, 4, 5]]


In [17]:
tensor_from_vector1d = torch.tensor(data_vector1d)
print(tensor_from_vector1d)

tensor([1, 2, 3, 4])


In [18]:
tensor_from_vector2d = torch.tensor(data_vector2d)
print(tensor_from_vector2d)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])


# 2 simple operation to tensor
* member function of tensor
* in-built function in libtorch

In [23]:
a = torch.rand((2,3))
print(a)

tensor([[0.8825, 0.2882, 0.7084],
        [0.8185, 0.6175, 0.3748]])


In [25]:
b = a.reshape((3,2))
print(b)

tensor([[0.8825, 0.2882],
        [0.7084, 0.8185],
        [0.6175, 0.3748]])


In [26]:
c = a.pow(2)
print(c)

tensor([[0.7788, 0.0831, 0.5018],
        [0.6699, 0.3814, 0.1405]])


In [27]:
d = a.abs()
print(d)

tensor([[0.8825, 0.2882, 0.7084],
        [0.8185, 0.6175, 0.3748]])


In [28]:
e = torch.abs(a)
print(e)

tensor([[0.8825, 0.2882, 0.7084],
        [0.8185, 0.6175, 0.3748]])


# 3 explore properties of tensor

In [39]:
tensor_from_vector2d.size()

torch.Size([2, 4])

In [37]:
tensor_from_vector2d.dtype

torch.int64

In [40]:
tensor_from_vector2d.device

device(type='cpu')

In [41]:
tensor_from_vector2d.layout

torch.strided

In [43]:
tensor_from_vector2d.requires_grad

False

# 4 configure properties of the tensor

> torch.tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor

In [45]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [46]:
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

## properties conversion

In [49]:
tensor = torch.randn(2, 2)  # Initially dtype=float32, device=cpu

In [50]:
tensor.to(torch.float64)

tensor([[-0.4925, -0.5312],
        [ 0.2057,  0.2802]], dtype=torch.float64)

In [51]:
cuda0 = torch.device('cuda:0')
tensor.to(cuda0)

tensor([[-0.4925, -0.5312],
        [ 0.2057,  0.2802]], device='cuda:0')

In [52]:
tensor.to(cuda0, dtype=torch.float64)

tensor([[-0.4925, -0.5312],
        [ 0.2057,  0.2802]], device='cuda:0', dtype=torch.float64)