In [2]:
import torch
import torch.nn as nn

/home/sz/anaconda3/envs/cling/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
torch.manual_seed(116)

In [4]:
a = torch.rand((3,4))
print(a)

tensor([[0.0432, 0.6826, 0.2691, 0.7010],
        [0.7327, 0.7858, 0.4593, 0.1238],
        [0.6378, 0.7911, 0.6816, 0.7845]])


# 1 SLICING AND EXTRACTING PARTS FROM TENSORS

## a extract a single element in tensor

In [5]:
print()
print("tensor[0,2] as tensor:\n")
a[0,2]


tensor[0,2] as tensor:



tensor(0.2691)

In [6]:
print("tensor[0,2] as value:\n")
a[0,2].item()

tensor[0,2] as value:



0.26909613609313965

## b slice a tensor along a dimension at a given index

In [7]:
b = a[:,1]

In [8]:
b

tensor([0.6826, 0.7858, 0.7911])

In [9]:
b.size()

torch.Size([3])

slice a tensor along a dimesion at given indices from a start-index up to - but not including - an end-index using a given step size

In [10]:
c = a[:2, :]

In [11]:
c

tensor([[0.0432, 0.6826, 0.2691, 0.7010],
        [0.7327, 0.7858, 0.4593, 0.1238]])

In [12]:
a[:2, 1]

tensor([0.6826, 0.7858])

In [13]:
a[:2, 1:]

tensor([[0.6826, 0.2691, 0.7010],
        [0.7858, 0.4593, 0.1238]])

In [14]:
a[..., 1:]

tensor([[0.6826, 0.2691, 0.7010],
        [0.7858, 0.4593, 0.1238],
        [0.7911, 0.6816, 0.7845]])

## c Select specific columns of each row in a torch Tensor

In [15]:
x = torch.arange(12).reshape(3, 4) * 1.0
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [16]:
position = torch.tensor([1,0,3])
print(position)
print(position.shape)
print(position.view(-1,1).shape)

tensor([1, 0, 3])
torch.Size([3])
torch.Size([3, 1])


In [17]:
selected_slement = x.gather(1, position.view(-1,1))
print(selected_slement)
print(selected_slement.shape)

tensor([[ 1.],
        [ 4.],
        [11.]])
torch.Size([3, 1])


## d for more than 2d dimensions

In [19]:
data_nd = torch.randn((2,3,4))
print(data_nd)

tensor([[[-1.4824,  1.7283,  0.1903,  0.0314],
         [ 1.3560, -1.0396, -0.4231, -0.0573],
         [ 0.3742, -0.1944, -0.0774,  0.3401]],

        [[ 1.5562,  0.1314,  0.2545, -0.5856],
         [-0.1950, -0.0822,  0.8732, -2.1623],
         [-1.5700, -0.5433, -1.2105, -0.6984]]])


In [20]:
print(data_nd[...,:2, 1:])

tensor([[[ 1.7283,  0.1903,  0.0314],
         [-1.0396, -0.4231, -0.0573]],

        [[ 0.1314,  0.2545, -0.5856],
         [-0.0822,  0.8732, -2.1623]]])


# 2 setter

In [13]:
print(a)

a[1,2] = 1.1
print("-----------------")
print(a)

tensor([[0.2693, 0.5362, 0.2260, 0.8407],
        [0.0762, 0.0125, 0.7928, 0.1319],
        [0.3522, 0.6191, 0.7726, 0.3371]])
-----------------
tensor([[0.2693, 0.5362, 0.2260, 0.8407],
        [0.0762, 0.0125, 1.1000, 0.1319],
        [0.3522, 0.6191, 0.7726, 0.3371]])


In [14]:
print(a)

a[:,1] = 1.1
print("-----------------")
print(a)

tensor([[0.2693, 0.5362, 0.2260, 0.8407],
        [0.0762, 0.0125, 1.1000, 0.1319],
        [0.3522, 0.6191, 0.7726, 0.3371]])
-----------------
tensor([[0.2693, 1.1000, 0.2260, 0.8407],
        [0.0762, 1.1000, 1.1000, 0.1319],
        [0.3522, 1.1000, 0.7726, 0.3371]])


In [17]:
b = torch.ones((2,3))
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
a[:2,1:] = b
print(a)

tensor([[0.2693, 1.0000, 1.0000, 1.0000],
        [0.0762, 1.0000, 1.0000, 1.0000],
        [0.3522, 1.1000, 0.7726, 0.3371]])


In [21]:
data_nd[...,:2, 1:] = 11.111
print(data_nd)

tensor([[[-1.4824, 11.1110, 11.1110, 11.1110],
         [ 1.3560, 11.1110, 11.1110, 11.1110],
         [ 0.3742, -0.1944, -0.0774,  0.3401]],

        [[ 1.5562, 11.1110, 11.1110, 11.1110],
         [-0.1950, 11.1110, 11.1110, 11.1110],
         [-1.5700, -0.5433, -1.2105, -0.6984]]])


## checkout deep copy and shallow copy in pytorch

In [20]:
print(a)

tensor([[0.2693, 1.0000, 1.0000, 1.0000],
        [0.0762, 1.0000, 1.0000, 1.0000],
        [0.3522, 1.1000, 0.7726, 0.3371]])


In [21]:
b = a[:2,1:]
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
b[0,1] = 22
print(b)

tensor([[ 1., 22.,  1.],
        [ 1.,  1.,  1.]])


In [25]:
print(a)

tensor([[ 0.2693,  1.0000, 22.0000,  1.0000],
        [ 0.0762,  1.0000,  1.0000,  1.0000],
        [ 0.3522,  1.1000,  0.7726,  0.3371]])


In [32]:
def clone_vs_deepcopy():
    import copy
    x = torch.tensor([1,2,3.0])
    y = x
    x_clone = x.clone()
    x_deep_clone = copy.deepcopy(x)
    print("raw x = {}".format(x))
    
    x.mul_(-1)
    print("-------------------")
    print("x = {}".format(x))
    print("y = {}".format(y))
    print("x_clone = {}".format(x_clone))
    print("x_deep_clone = {}".format(x_deep_clone))
     

In [33]:
clone_vs_deepcopy()

raw x = tensor([1., 2., 3.])
-------------------
x = tensor([-1., -2., -3.])
y = tensor([-1., -2., -3.])
x_clone = tensor([1., 2., 3.])
x_deep_clone = tensor([1., 2., 3.])


In [34]:
print(a)

tensor([[ 0.2693,  1.0000, 22.0000,  1.0000],
        [ 0.0762,  1.0000,  1.0000,  1.0000],
        [ 0.3522,  1.1000,  0.7726,  0.3371]])


In [37]:
c = a[:2,1:].clone()
print(c)

tensor([[ 1., 22.,  1.],
        [ 1.,  1.,  1.]])


In [38]:
c[0, 0] = 21
print(c)

tensor([[21., 22.,  1.],
        [ 1.,  1.,  1.]])


In [39]:
print(a)

tensor([[ 0.2693,  1.0000, 22.0000,  1.0000],
        [ 0.0762,  1.0000,  1.0000,  1.0000],
        [ 0.3522,  1.1000,  0.7726,  0.3371]])
