# How to use an optimizer

To use torch.optim you have to construct an optimizer object, that will hold the current state and will update the parameters based on the computed gradients.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
torch.tensor([1.0, 2.0]).unsqueeze(-1)

tensor([[1.],
        [2.]])

note: the grad of a **parameter** can be overwritten

In [3]:
custom_weights = nn.Parameter(torch.tensor([1.0, 2.0]).unsqueeze(-1))
print(custom_weights)

Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True)


In [4]:
custom_weights.grad = torch.ones((2,1))
print(custom_weights.grad)

tensor([[1.],
        [1.]])


In [5]:
learning_rate = 0.1
optimizer = optim.SGD([custom_weights], lr=learning_rate)

In [6]:
optimizer.step()

In [7]:
print(custom_weights)

Parameter containing:
tensor([[0.9000],
        [1.9000]], requires_grad=True)


## understand SGD

In [8]:
class CustomSGDOptimizer(object):
    def __init__(self, param, lr):
        self.param = param
        self.lr = lr
    
    def step(self):
        with torch.no_grad():
            self.param.add_(self.param.grad, alpha=-1 * self.lr)

In [9]:
custom_weights = nn.Parameter(torch.tensor([1.0, 2.0]).unsqueeze(-1))
print(custom_weights)

Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True)


In [10]:
custom_weights.grad = torch.ones((2,1))
print(custom_weights.grad)

tensor([[1.],
        [1.]])


In [11]:
custom_sgd_optimizer = CustomSGDOptimizer(custom_weights, learning_rate)
custom_sgd_optimizer.step()

In [12]:
print(custom_weights)

Parameter containing:
tensor([[0.9000],
        [1.9000]], requires_grad=True)
