In [1]:
import torch
import torch.nn as nn
from torch.nn.functional import pad
import numpy as np

# Conv1d

In [2]:
# torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, 
#                 padding=0, dilation=1, groups=1, bias=True, 
#                 padding_mode='zeros', device=None, dtype=None)

Applies a 1D convolution over an input signal composed of several input planes.

- Input: $(N,C_{in},L)$ or $(C_{in},L_{in})$
- Output: $(N,C_{out},L)$ or $(C_{out},L_{out})$

where $N$ is a batch size, $C$ denotes a number of channels, $L$ is a length of signal sequence.

## 2D input

### shape of output

$$L_{out} = \lfloor \frac{L_{in} + 2 \times padding - dilation \times (kernel\_size - 1) - 1}{stride} + 1 \rfloor$$

In [3]:
number_channel = 6
sequence_length = 5
x  = torch.arange(number_channel * sequence_length, dtype=torch.float32).reshape(number_channel, sequence_length)
print(x.shape)

torch.Size([6, 5])


In [4]:
# kernel_size: Size of the convolving kernel, equals 2
conv1d = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2)
output = conv1d.forward(x)
print(output.shape)

torch.Size([4, 4])


In [5]:
# stride: Stride of the convolution, equals 2
conv1d_with_stride = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, stride=2)
output_with_stride = conv1d_with_stride.forward(x)
print(output_with_stride.shape)

torch.Size([4, 2])


In [6]:
# padding: Padding added to both sides of the input, equals 1
conv1d_with_padding = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, padding=1)
output_with_padding = conv1d_with_padding.forward(x)
print(output_with_padding.shape)

torch.Size([4, 6])


In [7]:
# dilation: Spacing between kernel elements, equals 2
conv1d_with_dilation = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, dilation=2)
output_with_dilation = conv1d_with_dilation.forward(x)
print(output_with_dilation.shape)

torch.Size([4, 3])


In [8]:
# groups: Number of blocked connections from input channels to output channels, equals 2
conv1d_with_groups = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, groups=2)
output_with_groups = conv1d_with_groups.forward(x)
print(output_with_groups.shape)

torch.Size([4, 4])


In [9]:
# bias: If True, adds a learnable bias to the output, equals False
conv1d_without_bias = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, bias=False)
output_without_bias = conv1d_without_bias.forward(x)
print(output_without_bias.shape)

torch.Size([4, 4])


### value of output

In [11]:
print(x)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.]])


In [10]:
# kernel_size: Size of the convolving kernel, equals 2
# conv1d = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2)
conv1d.weight.data.fill_(1.0)
conv1d.bias.data.fill_(0.0)
output_value = conv1d.forward(x)
print(output_value)

tensor([[156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.]], grad_fn=<SqueezeBackward1>)


In [12]:
# stride: Stride of the convolution, equals 2
# conv1d_with_stride = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, stride=2)
conv1d_with_stride.weight.data.fill_(1.0)
conv1d_with_stride.bias.data.fill_(0.0)
output_value_with_stride = conv1d_with_stride.forward(x)
print(output_value_with_stride)

tensor([[156., 180.],
        [156., 180.],
        [156., 180.],
        [156., 180.]], grad_fn=<SqueezeBackward1>)


In [13]:
# padding: Padding added to both sides of the input, equals 1
# conv1d_with_padding = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, padding=1)
conv1d_with_padding.weight.data.fill_(1.0)
conv1d_with_padding.bias.data.fill_(0.0)
output_value_with_padding = conv1d_with_padding.forward(x)
print(output_value_with_padding)

tensor([[ 75., 156., 168., 180., 192.,  99.],
        [ 75., 156., 168., 180., 192.,  99.],
        [ 75., 156., 168., 180., 192.,  99.],
        [ 75., 156., 168., 180., 192.,  99.]], grad_fn=<SqueezeBackward1>)


In [15]:
# dilation: Spacing between kernel elements, equals 2
# conv1d_with_dilation = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, dilation=2)
conv1d_with_dilation.weight.data.fill_(1.0)
conv1d_with_dilation.bias.data.fill_(0.0)
output_value_with_dilation = conv1d_with_dilation.forward(x)
print(output_value_with_dilation)

tensor([[162., 174., 186.],
        [162., 174., 186.],
        [162., 174., 186.],
        [162., 174., 186.]], grad_fn=<SqueezeBackward1>)


In [16]:
# groups: Number of blocked connections from input channels to output channels, equals 2
# conv1d_with_groups = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, groups=2)
conv1d_with_groups.weight.data.fill_(1.0)
conv1d_with_groups.bias.data.fill_(0.0)
output_value_with_groups = conv1d_with_groups.forward(x)
print(output_value_with_groups)

tensor([[ 33.,  39.,  45.,  51.],
        [ 33.,  39.,  45.,  51.],
        [123., 129., 135., 141.],
        [123., 129., 135., 141.]], grad_fn=<SqueezeBackward1>)


In [18]:
# bias: If True, adds a learnable bias to the output, equals False
# conv1d_without_bias = nn.Conv1d(in_channels=number_channel, out_channels=4, kernel_size=2, bias=False)
conv1d_without_bias.weight.data.fill_(1.0)
output_value_without_bias = conv1d_without_bias.forward(x)
print(output_value_without_bias)

tensor([[156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.]], grad_fn=<SqueezeBackward1>)


### how does `Conv1d` work with 2D input

In [19]:
# conv1d.weight.data.fill_(1.0)
# conv1d.bias.data.fill_(0.0)
print('weight: {}\n'.format(conv1d.weight.data.shape), conv1d.weight.data)
print('bias: {}\n'.format(conv1d.bias.data.shape), conv1d.bias.data)

weight: torch.Size([4, 6, 2])
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
bias: torch.Size([4])
 tensor([0., 0., 0., 0.])


In [20]:
output = conv1d.forward(x)
print(output)

tensor([[156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.]], grad_fn=<SqueezeBackward1>)


In [21]:
def conv_1d(x, weight, bias, stride=1, padding=0): 
    out_channels, in_channels, kernel_size = weight.shape
    X = pad(x, pad=(padding, padding, 0, 0), mode='constant', value=0)
    Y = torch.zeros((out_channels, int(np.ceil((X.shape[1] - kernel_size + 2 * padding + 1) / stride))))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[:, stride * j:stride * j + kernel_size] * weight[i]).sum() + bias[i]
    return Y

In [22]:
print('result of conv_1d: \n', conv_1d(x, weight=conv1d.weight.data, bias=conv1d.bias.data))

result of conv_1d: 
 tensor([[156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.],
        [156., 168., 180., 192.]])


## how does parameter `groups` work

In [23]:
x = torch.arange(4, dtype=torch.float32).view(4, 1)
print(x)

tensor([[0.],
        [1.],
        [2.],
        [3.]])


In [24]:
# groups=1
conv1d_groups1 = nn.Conv1d(in_channels=4, out_channels=4, kernel_size=1, groups=1, bias=False)
conv1d_groups1.weight.data = torch.arange(16, dtype=torch.float32).view(4,4,1)

output_groups1 = conv1d_groups1(x)
print(conv1d_groups1.weight.data)
print(output_groups1) # 0*0+1*1+2*2+3*3=14, 0*4+1*5+2*6+3*7=38

tensor([[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]])
tensor([[14.],
        [38.],
        [62.],
        [86.]], grad_fn=<SqueezeBackward1>)


In [25]:
# groups=2
conv1d_groups2 = nn.Conv1d(in_channels=4, out_channels=4, kernel_size=1, groups=2, bias=False)
conv1d_groups2.weight.data = torch.arange(8, dtype=torch.float32).view(4,2,1)

output_groups2 = conv1d_groups2(x)
print(conv1d_groups2.weight.data)
print(output_groups2) # 0*0+1*1=1, 0*2+1*3=3, 2*4+3*5=23, 2*6+3*7=33

tensor([[[0.],
         [1.]],

        [[2.],
         [3.]],

        [[4.],
         [5.]],

        [[6.],
         [7.]]])
tensor([[ 1.],
        [ 3.],
        [23.],
        [33.]], grad_fn=<SqueezeBackward1>)


In [26]:
# groups=4
conv1d_groups4 = nn.Conv1d(in_channels=4, out_channels=4, kernel_size=1, groups=4, bias=False)
conv1d_groups4.weight.data = torch.arange(4, dtype=torch.float32).view(4,1,1)

output_groups4 = conv1d_groups4(x)
print(conv1d_groups4.weight.data)
print(output_groups4) # 0*0+1*1=1, 0*0=0, 1*1=1, 2*2=2, 3*3=9

tensor([[[0.]],

        [[1.]],

        [[2.]],

        [[3.]]])
tensor([[0.],
        [1.],
        [4.],
        [9.]], grad_fn=<SqueezeBackward1>)


## 3D input

In [27]:
batch_size = 2
x_3d = torch.arange(batch_size * number_channel * sequence_length, dtype=torch.float).reshape(batch_size, number_channel, sequence_length)
print(x_3d)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.]],

        [[30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.],
         [40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]])


In [28]:
# kernel_size: Size of the convolving kernel, equals 2
output_3d = conv1d.forward(x_3d)
print(output_3d)

tensor([[[156., 168., 180., 192.],
         [156., 168., 180., 192.],
         [156., 168., 180., 192.],
         [156., 168., 180., 192.]],

        [[516., 528., 540., 552.],
         [516., 528., 540., 552.],
         [516., 528., 540., 552.],
         [516., 528., 540., 552.]]], grad_fn=<ConvolutionBackward0>)


In [29]:
# stride: Stride of the convolution, equals 2
conv1d_with_stride.weight.data.fill_(1.0)
conv1d_with_stride.bias.data.fill_(0.0)
output_3d_with_stride = conv1d_with_stride.forward(x_3d)
print(output_3d_with_stride)

tensor([[[156., 180.],
         [156., 180.],
         [156., 180.],
         [156., 180.]],

        [[516., 540.],
         [516., 540.],
         [516., 540.],
         [516., 540.]]], grad_fn=<ConvolutionBackward0>)


In [30]:
# padding: Padding added to both sides of the input, equals 1
conv1d_with_padding.weight.data.fill_(1.0)
conv1d_with_padding.bias.data.fill_(0.0)
output_3d_with_padding = conv1d_with_padding.forward(x_3d)
print(output_3d_with_padding)

tensor([[[ 75., 156., 168., 180., 192.,  99.],
         [ 75., 156., 168., 180., 192.,  99.],
         [ 75., 156., 168., 180., 192.,  99.],
         [ 75., 156., 168., 180., 192.,  99.]],

        [[255., 516., 528., 540., 552., 279.],
         [255., 516., 528., 540., 552., 279.],
         [255., 516., 528., 540., 552., 279.],
         [255., 516., 528., 540., 552., 279.]]],
       grad_fn=<ConvolutionBackward0>)


In [31]:
# dilation: Spacing between kernel elements, equals 2
conv1d_with_dilation.weight.data.fill_(1.0)
conv1d_with_dilation.bias.data.fill_(0.0)
output_3d_with_dilation = conv1d_with_dilation.forward(x_3d)
print(output_3d_with_dilation)

tensor([[[162., 174., 186.],
         [162., 174., 186.],
         [162., 174., 186.],
         [162., 174., 186.]],

        [[522., 534., 546.],
         [522., 534., 546.],
         [522., 534., 546.],
         [522., 534., 546.]]], grad_fn=<ConvolutionBackward0>)


In [32]:
# groups: Number of blocked connections from input channels to output channels, equals 2
conv1d_with_groups.weight.data.fill_(1.0)
conv1d_with_groups.bias.data.fill_(0.0)
output_3d_with_groups = conv1d_with_groups.forward(x_3d)
print(output_3d_with_groups)

tensor([[[ 33.,  39.,  45.,  51.],
         [ 33.,  39.,  45.,  51.],
         [123., 129., 135., 141.],
         [123., 129., 135., 141.]],

        [[213., 219., 225., 231.],
         [213., 219., 225., 231.],
         [303., 309., 315., 321.],
         [303., 309., 315., 321.]]], grad_fn=<ConvolutionBackward0>)


In [33]:
# bias: If True, adds a learnable bias to the output, equals False
conv1d_without_bias.weight.data.fill_(1.0)
output_3d_without_bias = conv1d_without_bias.forward(x_3d)
print(output_3d_without_bias)

tensor([[[156., 168., 180., 192.],
         [156., 168., 180., 192.],
         [156., 168., 180., 192.],
         [156., 168., 180., 192.]],

        [[516., 528., 540., 552.],
         [516., 528., 540., 552.],
         [516., 528., 540., 552.],
         [516., 528., 540., 552.]]], grad_fn=<ConvolutionBackward0>)


# Conv2d

In [34]:
# torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, 
#                 padding=0, dilation=1, groups=1, bias=True, 
#                 padding_mode='zeros', device=None, dtype=None)

Applies a 2D convolution over an input signal composed of several input planes.

- Input: $(N,C_{in},H_{in},W_{in})$ or $(C_{in},H_{in},W_{in})$
- Output: $(N,C_{out},H_{out},W_{out})$ or $(C_{out},H_{out},W_{out})$

where $N$ is a batch size, $C$ denotes a number of channels, $H$ is height of input planes in pixels, and $W$ is width in pixels.

In [35]:
batch_size = 3
in_channels = 2
height = 4
width = 5
x_4d = torch.arange(batch_size * in_channels * height * width, dtype=torch.float).reshape(batch_size, in_channels, height, width)
print(x_4d)

tensor([[[[  0.,   1.,   2.,   3.,   4.],
          [  5.,   6.,   7.,   8.,   9.],
          [ 10.,  11.,  12.,  13.,  14.],
          [ 15.,  16.,  17.,  18.,  19.]],

         [[ 20.,  21.,  22.,  23.,  24.],
          [ 25.,  26.,  27.,  28.,  29.],
          [ 30.,  31.,  32.,  33.,  34.],
          [ 35.,  36.,  37.,  38.,  39.]]],


        [[[ 40.,  41.,  42.,  43.,  44.],
          [ 45.,  46.,  47.,  48.,  49.],
          [ 50.,  51.,  52.,  53.,  54.],
          [ 55.,  56.,  57.,  58.,  59.]],

         [[ 60.,  61.,  62.,  63.,  64.],
          [ 65.,  66.,  67.,  68.,  69.],
          [ 70.,  71.,  72.,  73.,  74.],
          [ 75.,  76.,  77.,  78.,  79.]]],


        [[[ 80.,  81.,  82.,  83.,  84.],
          [ 85.,  86.,  87.,  88.,  89.],
          [ 90.,  91.,  92.,  93.,  94.],
          [ 95.,  96.,  97.,  98.,  99.]],

         [[100., 101., 102., 103., 104.],
          [105., 106., 107., 108., 109.],
          [110., 111., 112., 113., 114.],
          [115., 116

In [36]:
# kernel_size: Size of the convolving kernel, equals (2, 1)
conv2d = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1))
conv2d.weight.data.fill_(1.0)
conv2d.bias.data.fill_(0.0)
output_conv2d = conv2d.forward(x_4d)
print(output_conv2d.shape)
print(output_conv2d)

torch.Size([3, 4, 3, 5])
tensor([[[[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]]],


        [[[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 

In [37]:
# stride: Stride of the convolution, equals (2,1)
conv2d_with_stride = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1), stride=(2, 1))
conv2d_with_stride.weight.data.fill_(1.0)
conv2d_with_stride.bias.data.fill_(0.0)
output_conv2d__with_stride = conv2d_with_stride.forward(x_4d)
print(output_conv2d__with_stride.shape)
print(output_conv2d__with_stride)

torch.Size([3, 4, 2, 5])
tensor([[[[ 50.,  54.,  58.,  62.,  66.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 90.,  94.,  98., 102., 106.]]],


        [[[210., 214., 218., 222., 226.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [250., 254., 258., 262., 266.]]],


        [[[370., 374., 378., 382., 386.],
          [410., 414., 418., 422., 426.]],

         [[370., 374., 378., 382., 386.],
          [410., 414., 418., 422., 426.]],

         [[370., 374., 378., 382., 386.],
          [410., 414., 418., 422., 426.]],

         [[370., 374., 37

In [38]:
# padding: Padding added to both sides of the input, equals (2,1)
conv2d_with_padding = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1), padding=(2, 1))
conv2d_with_padding.weight.data.fill_(1.0)
conv2d_with_padding.bias.data.fill_(0.0)
output_conv2d_with_padding = conv2d_with_padding.forward(x_4d)
print(output_conv2d_with_padding.shape)
print(output_conv2d_with_padding)

torch.Size([3, 4, 7, 7])
tensor([[[[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
          [  0.,  20.,  22.,  24.,  26.,  28.,   0.],
          [  0.,  50.,  54.,  58.,  62.,  66.,   0.],
          [  0.,  70.,  74.,  78.,  82.,  86.,   0.],
          [  0.,  90.,  94.,  98., 102., 106.,   0.],
          [  0.,  50.,  52.,  54.,  56.,  58.,   0.],
          [  0.,   0.,   0.,   0.,   0.,   0.,   0.]],

         [[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
          [  0.,  20.,  22.,  24.,  26.,  28.,   0.],
          [  0.,  50.,  54.,  58.,  62.,  66.,   0.],
          [  0.,  70.,  74.,  78.,  82.,  86.,   0.],
          [  0.,  90.,  94.,  98., 102., 106.,   0.],
          [  0.,  50.,  52.,  54.,  56.,  58.,   0.],
          [  0.,   0.,   0.,   0.,   0.,   0.,   0.]],

         [[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
          [  0.,  20.,  22.,  24.,  26.,  28.,   0.],
          [  0.,  50.,  54.,  58.,  62.,  66.,   0.],
          [  0.,  70.,  74.,  78.,  82.,  86.,   0.],

In [39]:
# dilation: dilation added to both sides of the input, equals (2,1)
conv2d_with_dilation = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1), dilation=(2, 1))
conv2d_with_dilation.weight.data.fill_(1.0)
conv2d_with_dilation.bias.data.fill_(0.0)
output_conv2d_with_dilation = conv2d_with_dilation.forward(x_4d)
print(output_conv2d_with_dilation.shape)
print(output_conv2d_with_dilation)

torch.Size([3, 4, 2, 5])
tensor([[[[ 60.,  64.,  68.,  72.,  76.],
          [ 80.,  84.,  88.,  92.,  96.]],

         [[ 60.,  64.,  68.,  72.,  76.],
          [ 80.,  84.,  88.,  92.,  96.]],

         [[ 60.,  64.,  68.,  72.,  76.],
          [ 80.,  84.,  88.,  92.,  96.]],

         [[ 60.,  64.,  68.,  72.,  76.],
          [ 80.,  84.,  88.,  92.,  96.]]],


        [[[220., 224., 228., 232., 236.],
          [240., 244., 248., 252., 256.]],

         [[220., 224., 228., 232., 236.],
          [240., 244., 248., 252., 256.]],

         [[220., 224., 228., 232., 236.],
          [240., 244., 248., 252., 256.]],

         [[220., 224., 228., 232., 236.],
          [240., 244., 248., 252., 256.]]],


        [[[380., 384., 388., 392., 396.],
          [400., 404., 408., 412., 416.]],

         [[380., 384., 388., 392., 396.],
          [400., 404., 408., 412., 416.]],

         [[380., 384., 388., 392., 396.],
          [400., 404., 408., 412., 416.]],

         [[380., 384., 38

In [40]:
# groups: groups added to both sides of the input, equals 2
conv2d_with_groups = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1), groups=2)
conv2d_with_groups.weight.data.fill_(1.0)
conv2d_with_groups.bias.data.fill_(0.0)
output_conv2d_with_groups = conv2d_with_groups.forward(x_4d)
print(output_conv2d_with_groups.shape)
print(output_conv2d_with_groups)

torch.Size([3, 4, 3, 5])
tensor([[[[  5.,   7.,   9.,  11.,  13.],
          [ 15.,  17.,  19.,  21.,  23.],
          [ 25.,  27.,  29.,  31.,  33.]],

         [[  5.,   7.,   9.,  11.,  13.],
          [ 15.,  17.,  19.,  21.,  23.],
          [ 25.,  27.,  29.,  31.,  33.]],

         [[ 45.,  47.,  49.,  51.,  53.],
          [ 55.,  57.,  59.,  61.,  63.],
          [ 65.,  67.,  69.,  71.,  73.]],

         [[ 45.,  47.,  49.,  51.,  53.],
          [ 55.,  57.,  59.,  61.,  63.],
          [ 65.,  67.,  69.,  71.,  73.]]],


        [[[ 85.,  87.,  89.,  91.,  93.],
          [ 95.,  97.,  99., 101., 103.],
          [105., 107., 109., 111., 113.]],

         [[ 85.,  87.,  89.,  91.,  93.],
          [ 95.,  97.,  99., 101., 103.],
          [105., 107., 109., 111., 113.]],

         [[125., 127., 129., 131., 133.],
          [135., 137., 139., 141., 143.],
          [145., 147., 149., 151., 153.]],

         [[125., 127., 129., 131., 133.],
          [135., 137., 139., 141., 

In [41]:
# bias: If True, adds a learnable bias to the output, equals False
conv2d_without_bias = nn.Conv2d(in_channels=in_channels, out_channels=4, kernel_size=(2, 1), bias=False)
conv2d_without_bias.weight.data.fill_(1.0)
output_conv2d_without_bias = conv2d_without_bias.forward(x_4d)
print(output_conv2d_without_bias.shape)
print(output_conv2d_without_bias)

torch.Size([3, 4, 3, 5])
tensor([[[[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]],

         [[ 50.,  54.,  58.,  62.,  66.],
          [ 70.,  74.,  78.,  82.,  86.],
          [ 90.,  94.,  98., 102., 106.]]],


        [[[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 246.],
          [250., 254., 258., 262., 266.]],

         [[210., 214., 218., 222., 226.],
          [230., 234., 238., 242., 