# TORCH.TENSOR

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

In [6]:
import torch

## Data types

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

> https://pytorch.org/docs/stable/tensors.html

## Initializing and basic operations

In [7]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

> A tensor of specific data type can be constructed by passing a torch.dtype and/or a torch.device to a constructor or tensor creation op:

In [8]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [9]:
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)