# Mean

Returns the mean value of each row of the input tensor in the given dimension dim. If dim is a list of dimensions, reduce over all of them.

If keepdim is True, the output tensor is of the same size as input except in the dimension(s) dim where it is of size 1. Otherwise, dim is squeezed (see torch.squeeze()), resulting in the output tensor having 1 (or len(dim)) fewer dimension(s).

In [2]:
import torch

In [3]:
tensor = torch.arange(24).reshape((2,3,4)).float()
print(tensor)
print(tensor.shape)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
torch.Size([2, 3, 4])


In [10]:
print(torch.mean(tensor,dim=0,keepdim=True))
print(torch.mean(tensor,dim=0,keepdim=True).shape)

tensor([[[ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.]]])
torch.Size([1, 3, 4])


In [8]:
print(torch.mean(tensor,dim=1,keepdim=True))
print(torch.mean(tensor,dim=1,keepdim=True).shape)

tensor([[[ 4.,  5.,  6.,  7.]],

        [[16., 17., 18., 19.]]])
torch.Size([2, 1, 4])


In [11]:
print(torch.mean(tensor,dim=2,keepdim=True))
print(torch.mean(tensor,dim=2,keepdim=True).shape)

tensor([[[ 1.5000],
         [ 5.5000],
         [ 9.5000]],

        [[13.5000],
         [17.5000],
         [21.5000]]])
torch.Size([2, 3, 1])


In [13]:
print(torch.mean(tensor,dim=(1,2),keepdim=True))
print(torch.mean(tensor,dim=(1,2),keepdim=True).shape)

tensor([[[ 5.5000]],

        [[17.5000]]])
torch.Size([2, 1, 1])


In [14]:
print(torch.mean(tensor,dim=(0,1),keepdim=True))
print(torch.mean(tensor,dim=(0,1),keepdim=True).shape)

tensor([[[10., 11., 12., 13.]]])
torch.Size([1, 1, 4])


In [12]:
print(torch.mean(tensor,dim=(0,2),keepdim=True))
print(torch.mean(tensor,dim=(0,2),keepdim=True).shape)

tensor([[[ 7.5000],
         [11.5000],
         [15.5000]]])
torch.Size([1, 3, 1])
