In [1]:
import torch
import torch.nn as nn

# Linear

Applies a linear transformation to the incoming data: y = xA^T + b

In [2]:
sample_size = 3
number_features = 4

x = torch.arange(sample_size*number_features).reshape(sample_size, number_features) * 1.0
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [3]:
linear = nn.Linear(in_features=number_features, out_features=1)

In [4]:
output = linear.forward(x)
print(output)

tensor([[0.8683],
        [4.0047],
        [7.1411]], grad_fn=<AddmmBackward0>)


## understand the linear function

In [5]:
linear.weight.data.fill_(1.0)
linear.bias.data.fill_(0.0)

tensor([0.])

In [6]:
output = linear.forward(x)
print(output)

tensor([[ 6.],
        [22.],
        [38.]], grad_fn=<AddmmBackward0>)


In [7]:
custom_weights = torch.ones((4,1))
print(custom_weights)

tensor([[1.],
        [1.],
        [1.],
        [1.]])


In [8]:
custom_output = x.matmul(custom_weights)
print(custom_output)

tensor([[ 6.],
        [22.],
        [38.]])
