In [2]:
import torch
import torch.nn as nn

In [8]:
w = torch.empty(3,5)
print("before param init: \n{}".format(w))

before param init: 
tensor([[2.1019e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


# 1.1 constant init

In [9]:
nn.init.constant_(w, 0.3)
print("after param init: \n{}".format(w))

after param init: 
tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])


# 1.2 ones init

In [10]:
nn.init.ones_(w)
print("after param init: \n{}".format(w))

after param init: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


# 1.3 zeros init

In [13]:
nn.init.zeros_(w)
print("after param init: \n{}".format(w))

after param init: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


# 1.4 uniform init

In [11]:
nn.init.uniform_(w, a=0.0, b=0.2)
print("after param init: \n{}".format(w))

after param init: 
tensor([[0.1334, 0.1481, 0.0873, 0.0549, 0.0836],
        [0.0879, 0.1342, 0.0190, 0.0243, 0.0833],
        [0.1841, 0.1628, 0.1085, 0.1762, 0.1280]])


# 1.5 normal init

In [12]:
nn.init.normal_(w, mean=0.0, std=1)
print("after param init: \n{}".format(w))

after param init: 
tensor([[-0.7240,  2.8742, -0.0042, -0.8570, -0.2146],
        [-0.1037, -1.1148,  0.5375,  0.3584,  0.3762],
        [-1.0913,  2.4409, -0.2740, -0.4937,  0.5900]])
